default: &default
  adapter: postgresql
  database: website_mgmt_development
  pool: 5
  encoding: unicode

development:
  <<: *default

test: &test
  <<: *default
  database: website_mgmt_test

production:
  <<: *default
  database: website_mgmt_production

cucumber:
  <<: *test
